# Generated by Django 4.2.8 on 2025-10-26 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary_coef', models.DecimalField(decimal_places=1, max_digits=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lalinapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('work_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Đi đúng giờ', 'Đi đúng giờ'), ('Đi làm trễ', 'Đi làm trễ')], default='Đi đúng giờ', max_length=20)),
                ('ot', models.IntegerField(blank=True, default=1, null=True)),
                ('late_time', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cccd', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Đại học', 'Đại học'), ('Cao đẳng', 'Cao đẳng')], max_length=20)),
                ('contract_period', models.CharField(max_length=20)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('working', 'Đang làm việc'), ('on_leave', 'Nghỉ phép'), ('resigned', 'Đã nghỉ việc')], default='working', max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lalinapp.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã xử lý', 'Đã xử lý')], default='Đang xử lý', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lalinapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đã duyệt', 'Đã duyệt'), ('Từ chối', 'Từ chối')], default='Đang chờ', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
