# Generated by Django 4.2.8 on 2025-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalinapp', '0002_auto_20251026_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
