# Generated by Django 4.2.8 on 2025-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalinapp', '0003_complaint_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='Không có tiêu đề', max_length=255),
        ),
    ]
