# Generated by Django 4.2.8 on 2025-10-26 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lalinapp', '0004_complaint_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timesheet',
            new_name='Sheet',
        ),
    ]
